In [2]:
# Importando o módulo Numpy
import numpy as np

In [3]:
# Criando array unidimensional
array1 = np.array([10, 20, 30, 40])

In [4]:
# Criando array bi-dimensional
array2 = np.array([[100, 83, 12], [43, 56, 78]])

In [5]:
array1

array([10, 20, 30, 40])

In [6]:
array2

array([[100,  83,  12],
       [ 43,  56,  78]])

In [7]:
# Verificando o formato (shape) do array
array1.shape

(4,)

In [8]:
# Verificando o formato (shape) do array
array2.shape

(2, 3)

In [9]:
array1.size

4

In [10]:
# Verificando o número de dimensões
array2.ndim

2

In [11]:
### Tudo em python é objeto, métodos e atributos
# Método - realiza ação no objeto
# Atributo - característica do objeto

In [12]:
# Método
array2.max()

100

In [13]:
# Atributo
array2.ndim

2

In [14]:
## Criando estruturas de addos com range

In [15]:
array3 = np.arange(15)

In [16]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
# Usando start/end (exclusive)
array4 = np.arange(0, 15, 5)

In [18]:
array4

array([ 0,  5, 10])

In [19]:
# Criando estrutura de dados com linspace

In [20]:
# Argumentos: (start, end, number of elements)
array5 = np.linspace(0, 3, 4); array5

array([0., 1., 2., 3.])

In [21]:
### Criando estruturas de dados com outras funções

In [22]:
## numpy.zeros

In [23]:
array6 = np.zeros((10, 8)); array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
## numpy.ones

In [25]:
# Array 2x3x2 de 1's
array7 = np.ones((2, 3, 3)); array7

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
## numpy.eye
array8 = np.eye(3); array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
## numpy.diag


In [28]:
# Matriz diagonal
array9 = np.diag((2,1,4,6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [29]:
## numpy.random.rand

In [30]:
np.random.seed(100) # Set seed
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [31]:
# A função randn(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

In [32]:
## numpy.empty

In [33]:
array12 = np.empty((3,2)); array12

array([[4.66059853e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [34]:
## numpy.tile

In [35]:
np.array([[9, 4], [3,7]])

array([[9, 4],
       [3, 7]])

In [36]:
np.tile(np.array([[9,4],[3,7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [37]:
np.tile(np.array([[9,4], [3,7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

In [38]:
## Tipos de Dados NumPy

In [39]:
array13 = np.array([8, -3, 5, 9], dtype = 'float')

In [40]:
array13

array([ 8., -3.,  5.,  9.])

In [41]:
array13.dtype

dtype('float64')

In [42]:
array14 = np.array([2, 4, 6, 8])

In [43]:
array14

array([2, 4, 6, 8])

In [44]:
array14.dtype

dtype('int64')

In [45]:
array15 = np.array([2.0, 4, 6, 8])

In [46]:
array15.dtype

dtype('float64')

In [47]:
array17 = np.array([True, False, True])

In [48]:
array17.dtype

dtype('bool')

In [49]:
array16 = np.array(['Análise', 'de'])

In [50]:
array16.dtype

dtype('<U7')

In [51]:
## Operadores com Array

In [52]:
array19 = np.arange(0, 30) * 5

In [53]:
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [54]:
# Elevendo um array a potencia
array20 = np.arange(5) ** 4

In [55]:
array20

array([  0,   1,  16,  81, 256])

In [56]:
# Somando numero a cada elemento do array
array21 = np.arange(0, 20) + 1; array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])