## Transposition and reshaping of arrays

In [1]:
# Importando o módulo Numpy
import numpy as np

In [2]:
array1 = np.array([[65,23,19],[41, 87, 10]]); array1

array([[65, 23, 19],
       [41, 87, 10]])

In [3]:
array1.T

array([[65, 41],
       [23, 87],
       [19, 10]])

In [4]:
np.transpose(array1)

array([[65, 41],
       [23, 87],
       [19, 10]])

## Broadcasting

In [5]:
array2 = np.array([[33, 34, 35]]); array2.T

array([[33],
       [34],
       [35]])

In [6]:
array2.T + array2

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])

## Transformando Matrizes em Vetores

In [7]:
array3 = np.array([np.arange(1,6), np.arange(10,15)]); array3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [8]:
array3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [10]:
array3.T

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

In [11]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

## Operadores Lógicos

In [12]:
np.random.seed(100)
array4 = np.random.randint(1, 10, size=(4,44)); array4

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3, 3, 3, 2, 1, 9, 5, 1, 7, 3, 5, 2, 6,
        4, 5, 5, 4, 8, 2, 2, 8, 8, 1, 3, 4, 3, 6, 9, 2, 1, 8, 7, 3, 1, 9],
       [3, 6, 2, 9, 2, 6, 5, 3, 9, 4, 6, 1, 4, 7, 4, 5, 8, 7, 4, 1, 5, 5,
        6, 8, 7, 7, 3, 5, 3, 8, 2, 7, 7, 1, 8, 3, 4, 6, 5, 3, 5, 4, 8, 1],
       [1, 6, 7, 7, 6, 7, 5, 8, 4, 3, 4, 9, 8, 2, 6, 4, 1, 7, 3, 4, 5, 9,
        9, 6, 3, 8, 6, 1, 9, 7, 3, 1, 6, 4, 3, 4, 7, 5, 2, 4, 2, 5, 9, 9],
       [3, 3, 8, 3, 2, 3, 8, 2, 1, 6, 4, 6, 3, 7, 2, 2, 6, 3, 6, 7, 5, 7,
        8, 8, 4, 1, 3, 6, 2, 2, 1, 4, 7, 8, 4, 7, 5, 9, 7, 6, 1, 1, 6, 2]])

In [13]:
np.any((array4 % 7) == 0)

True

In [14]:
np.any((array4 < 11))

True

## Reshaping

In [15]:
array5 = np.arange(1,16)

In [16]:
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
array5.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Ordenando array

In [18]:
array7 = np.array([[3,2], [10,-1]]); array7

array([[ 3,  2],
       [10, -1]])

In [19]:
# Ordenando por linhas
array7.sort(axis = 1)

In [20]:
array7

array([[ 2,  3],
       [-1, 10]])

In [24]:
array8 = array7.copy(); array8

array([[ 2,  3],
       [-1, 10]])

In [25]:
# Ordena por colunas
array8.sort(axis=0)

In [26]:
array8

array([[-1,  3],
       [ 2, 10]])